on:
  workflow_call:
    inputs:
      version:
        required: true
        type: "string"
        description: "Container basic version"
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"
      target:
        required: false
        default: "./build"
        type: "string"
        description: "Specify build base target dir"

permissions:
  contents: read
  packages: write

jobs:
  containerized:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: download target
        uses: actions/download-artifact@v3
        with:
          name: target
          path: |
            ${{ inputs.target }}

      - run: tree .

      - id: environments
        name: environments
        run: |
          echo "timestamp=$(date +%Y%m%d | cut -c 3-8)" >> "$GITHUB_OUTPUT"
          echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - id: meta 
        name: container meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,enable=${{ github.ref == format('refs/heads/{0}', 'master') }},pattern={{version}}-${{ steps.environments.outputs.timestamp }}rc-${{ steps.environments.outputs.short_sha }},value=${{ inputs.version }}
            type=semver,enable=${{ github.ref != format('refs/heads/{0}', 'master') }},pattern={{version}}-${{ steps.environments.outputs.timestamp }}alpha-${{ steps.environments.outputs.short_sha }},value=${{ inputs.version }}
            
      - name: authenticate
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push github
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.workdir }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
