on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"

    outputs:
      version:
        description: "Rust application version"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    outputs:
      version: ${{ steps.environments.outputs.version }}
    steps:
      - name: cache registry cache
        id: heliannuuthus-cargo-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-heliannuuthus-cargo-cache
      - name: build
        run: cargo install cargo-auditable && cargo auditable build --release
      - name: test
        run: cargo test --release --verbose
      - id: environments
        name: environments
        run: |
          echo "
          project=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name')
          version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          " >> "$GITHUB_OUTPUT"
      - name: upload target
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: |
            ${{ inputs.workdir }}target/release/${{ steps.environments.outputs.project }}
