on:
  workflow_call:
    inputs:
      version:
        required: true
        type: "string"
        description: "Container basic version"
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"

permissions:
  contents: read
  packages: write

jobs:
  containerized:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: load target
        uses: actions/download-artifact@v3
        with:
          name: target

      - id: environments
        name: environments
        run: |
          echo "timestamp=$(date +%Y%m%d | cut -c 3-8)" >> "$GITHUB_OUTPUT"
          echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: container meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,enable=${{ github.ref == format('refs/heads/{0}', 'master') }},pattern=${{ inputs.version }}-${{ steps.environments.outputs.timestamp }}rc-${{ steps.environments.outputs.short_sha }}
            type=semver,enable=${{ github.ref != format('refs/heads/{0}', 'master') }},pattern=${{ inputs.version }}-${{ steps.environments.outputs.timestamp }}alpha-${{ steps.environments.outputs.short_sha }}

      - name: authenticate
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push github
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
