on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run, default: current directory"

      node:
        required: false
        type: "string"
        default: "lts/*"
        description: "Specify node version, default: lts"

    outputs:
      PNPM_STORE:
        description: "pnpm package store path"
        value: ${{ jobs.setup.outputs.PNPM_STORE }}

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    outputs:
      PNPM_STORE: ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: pnpm cache dir
        id: pnpm-cache-dir
        run: echo "PNPM_STORE=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: restore node cache
        uses: actions/cache/restore@v3
        id: cache-restore-node_modules
        env:
          cache-name: cache-node_modules
        with:
          # caching node_modules
          path: |
            ${{ inputs.workdir }}node_modules
            **/node_modules
            **/.eslintcache
            ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE }}
          key: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-
            ${{ runner.os }}-pnpm-store-
            ${{ runner.os }}-

      - name: setup
        if: steps.cache-restore-node_modules.outputs.cache-hit != 'true'
        run: |
          pnpm i  
          pnpm i -g eslint
          pnpm i -g prettier

      - name: cache node modules
        if: steps.cache-restore-node_modules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        id: cache-save-node_modules
        env:
          cache-name: cache-node_modules
        with:
          # caching node_modules
          path: |
            ${{ inputs.workdir }}node_modules
            **/node_modules
            **/.eslintcache
            ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE }}
          key: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: restore node cache
        uses: actions/cache/restore@v3
        id: cache-restore-node_modules
        env:
          cache-name: cache-node_modules
        with:
          # caching node_modules
          path: |
            ${{ inputs.workdir }}node_modules
            **/node_modules
            **/.eslintcache
            ${{ needs.setup.outputs.PNPM_STORE }}
          key: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-
            ${{ runner.os }}-pnpm-store-
            ${{ runner.os }}-

      - name: lint
        run: |
          pnpm eslint .
          pnpm prettier . --check-debug

  security:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: restore node cache
        uses: actions/cache/restore@v3
        id: cache-restore-node_modules
        env:
          cache-name: cache-node_modules
        with:
          # caching node_modules
          path: |
            ${{ inputs.workdir }}node_modules
            **/node_modules
            **/.eslintcache
            ${{ needs.setup.outputs.PNPM_STORE }}
          key: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-
            ${{ runner.os }}-pnpm-store-
            ${{ runner.os }}-

      - name: audit
        run: |
          pnpm audit
