on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"

      build:
        required: false
        default: "build"
        type: "string"
        description: "Specify build command"

      test:
        required: false
        default: ""
        type: "string"
        description: "Specify test command"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - name: pnpm cache dir
        id: pnpm-cache-dir
        run: echo "name=dir::$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: cache node modules
        id: cache-node_modules
        uses: actions/cache/restore@v3
        env:
          cache-name: cache-node_modules
        with:
          # caching node_modules
          path: |
            node_modules
            **/node_modules
            **/.eslintcache
            ${{ steps.pnpm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: build
        if: ${{ inputs.build}}
        run: pnpm ${{ inputs.build }}

      - name: test
        if: ${{ inputs.test }}
        run: pnpm ${{ inputs.test }}
