on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache-dependency-path: "**/*.sum"
          
      - name: golangci-lint
        run: |
          ls -la
          go version 
          golangci-lint -vv

  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache-dependency-path: "**/*.sum"

      - name: gosec checkout
        run: |
          go version 
          tree $(go env GOPATH)/bin
          gosec -fmt=sarif -out=gosec.sarif ./...
