on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: cache registry cache
        id: heliannuuthus-golang-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/go
          key: ${{ runner.os }}-heliannuuthus-golang-cache
      - name: golangci-lint
        run: go version && tree $(go env GOPATH)/bin && golangci-lint -vv

  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: cache registry cache
        id: heliannuuthus-golang-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/go
          key: ${{ runner.os }}-heliannuuthus-golang-cache
      - name: gosec checkout
        run: go version && tree $(go env GOPATH)/bin && gosec -fmt=sarif -out=gosec.sarif ./...
