on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - id: cache-restore-golang
        uses: actions/setup-go@v5
        with: 
          go-version: "1.20"
          cache-dependency-path: "**/*.sum"

      - name: setup
        if: ${{ steps.cache-restore-golang.outputs.cache-hit != 'true'}}
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.1
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.18.2
          go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@v2.5.0
          go install github.com/jstemmer/go-junit-report/v2@v2.1.0