on:
  workflow_call:
    inputs:
      rust_workdir:
        required: false
        default: "./src-tauri"
        type: "string"
        description: "Specify all of rust steps where are run"
      node_workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of node steps where are run"
      node:
        required: false
        default: "lts/*"
        type: "string"
        description: "Specify node version, default: lts"
      build:
        required: false
        default: "build"
        type: "string"
        description: "Specify build command"
      test:
        required: false
        default: ""
        type: "string"
        description: "Specify test command"

jobs:
  build-tauri:
    
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-latest"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: ${{ inputs.node_workdir }}
    steps:
      - uses: actions/checkout@v4
      - name: linux install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.platform == 'ubuntu-latest'
        with:
          packages: libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf 
          version: rust-tauri-ci
          execute_install_scripts: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: pnpm cache dir
        id: pnpm-cache-dir
        run: echo "PNPM_STORE=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: restore node cache
        uses: actions/cache/restore@v4
        id: cache-restore-node_modules
        env:
          cache-name: cache-node_modules
        with:
          # caching node_modules
          path: |
            ${{ inputs.node_workdir }}node_modules
            **/node_modules
            **/.eslintcache
            ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE }}
          key: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-

      - name: setup
        if: steps.cache-restore-node_modules.outputs.cache-hit != 'true'
        run: |
          pnpm i
          pnpm i -g eslint
          pnpm i -g prettier

      - name: cache node modules
        if: ${{ steps.cache-restore-node_modules.outputs.cache-hit != 'true'}}
        uses: actions/cache/save@v4
        id: cache-save-node_modules
        env:
          cache-name: cache-node_modules
        with:
          # caching node_modules
          path: |
            ${{ inputs.node_workdir }}node_modules
            **/node_modules
            **/.eslintcache
            ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE }}
          key: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "${{ inputs.node_workdir }}/src-tauri"
          cache-targets: false

      - name: install frontend dependencies
        run: pnpm install && pnpm eslint --fix . && pnpm prettier --write .

      - id: environments
        name: environments
        run: |
          opt="--no-deps --format-version 1"
          if [ -d "src-tauri" ]; then
            opt="$opt --manifest-path src-tauri/Cargo.toml"
          fi
          echo "
          project=$(cargo metadata $opt | jq -r '.packages[0].name')
          version=$(cargo metadata $opt | jq -r '.packages[0].version')
          " >> "$GITHUB_OUTPUT"
        shell: bash

      
      - id: tauri-action
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ steps.environments.outputs.version }}
          releaseName: ${{ steps.environments.outputs.project }}
          releaseBody: ${{ github.event.head_commit.message }}
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: upload tauri-artifact
        uses: actions/upload-artifact@v3
        with:
          name: tauri-artifact
          path: |
              ${{ fromJSON(steps.tauri-action.outputs.artifactPaths)[0] }}
              ${{ fromJSON(steps.tauri-action.outputs.artifactPaths)[1] }}
              ${{ fromJSON(steps.tauri-action.outputs.artifactPaths)[2] }}

