on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of node steps where are run"

      node:
        required: false
        default: "lts/*"
        type: "string"
        description: "Specify node version, default: lts"

      toolchain:
        required: false
        default: "stable"
        type: "string"
        description: "Specify rust toolchain version, default: stable"

      build:
        required: false
        default: "build"
        type: "string"
        description: "Specify build command"

      test:
        required: false
        default: ""
        type: "string"
        description: "Specify test command"


jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: restore rust cache
        uses: actions/cache/restore@v4
        id: cache-restore-cargo
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-store-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-store-${{ env.cache-name }}-
      - name: setup
        if: ${{ steps.cache-restore-cargo.outputs.cache-hit != 'true' }}
        run: |
          rustup component add rustfmt clippy
          cargo install cargo-audit cargo2junit cargo-tarpaulin cargo-nextest

      - name: cache cargo
        if: ${{ steps.cache-restore-cargo.outputs.cache-hit != 'true' }}
        id: cache-save-cargo
        uses: actions/cache/save@v4
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-store-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

  lint:
    needs: [setup]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: restore rust cache
        uses: actions/cache/restore@v4
        id: cache-restore-cargo
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-store-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-store-${{ env.cache-name }}-
      - name: setup
        if: ${{ steps.cache-restore-cargo.outputs.cache-hit != 'true' }}
        run: |
          rustup component add rustfmt clippy
          cargo install cargo-audit cargo2junit cargo-tarpaulin cargo-nextest

      - name: cache cargo
        if: ${{ steps.cache-restore-cargo.outputs.cache-hit != 'true' }}
        id: cache-save-cargo
        uses: actions/cache/save@v4
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-store-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: lint
        run: |
          cargo fmt --all -- --check
          cargo check --no-default-features
          cargo clippy --all-targets --all-features -- -D warnings

  build:
    needs: [lint]
    outputs:
      project: ${{ steps.environments.outputs.project }}
      version: ${{ steps.environments.outputs.version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: restore rust cache
        uses: actions/cache/restore@v4
        id: cache-restore-cargo
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-store-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-store-${{ env.cache-name }}-
      - name: setup
        if: ${{ steps.cache-restore-cargo.outputs.cache-hit != 'true' }}
        run: |
          rustup component add rustfmt clippy
          cargo install cargo-audit cargo2junit cargo-tarpaulin cargo-nextest

      - name: cache cargo
        if: ${{ steps.cache-restore-cargo.outputs.cache-hit != 'true' }}
        id: cache-save-cargo
        uses: actions/cache/save@v4
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-store-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: test
        run: |
          cargo nextest run --target-dir target
          cargo tarpaulin --skip-clean --all-features --workspace --out xml --output-dir target

      - name: build
        run: cargo install cargo-auditable && cargo auditable build --release
      - id: environments
        name: environments
        run: |
          opt="--no-deps --format-version 1"
          if [ -d "src-tauri" ]; then
            opt="$opt --manifest-path src-tauri/Cargo.toml"
          fi
          echo "
          project=$(cargo metadata $opt | jq -r '.packages[0].name')
          version=$(cargo metadata $opt | jq -r '.packages[0].version')
          " >> "$GITHUB_OUTPUT"
        shell: bash

      - name: test
        run: |
          cargo nextest run --target-dir target
          cargo tarpaulin --skip-clean --all-features --workspace --out xml --output-dir target

      - name: build
        run: cargo install cargo-auditable && cargo auditable build --release
      - name: upload target
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
              ${{ inputs.workdir }}/src-tauri/target/release/${{ steps.environments.outputs.project }}
              ${{ inputs.workdir }}/src-tauri/target/default/report.xml
              ${{ inputs.workdir }}/src-tauri/target/cobertura.xml

  build-tauri:
    
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            target: "aarch64-apple-darwin"
          - platform: "macos-latest"
            target: "x86_64-apple-darwin"
          - platform: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
          - platform: "windows-latest"
            target: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4

      - name: linux install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.platform == 'ubuntu-latest'
        with:
          packages: libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf 
          version: rust-tauri-ci
          execute_install_scripts: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: pnpm cache dir
        id: pnpm-cache-dir
        run: echo "PNPM_STORE=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: restore node cache
        uses: actions/cache/restore@v4
        id: cache-restore-node_modules
        env:
          cache-name: cache-node_modules
        with:
          # caching node_modules
          path: |
            ${{ inputs.workdir }}node_modules
            **/node_modules
            **/.eslintcache
            ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE }}
          key: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-

      - name: setup
        if: steps.cache-restore-node_modules.outputs.cache-hit != 'true'
        run: |
          pnpm i
          pnpm i -g eslint
          pnpm i -g prettier

      - name: cache node modules
        if: ${{ steps.cache-restore-node_modules.outputs.cache-hit != 'true'}}
        uses: actions/cache/save@v4
        id: cache-save-node_modules
        env:
          cache-name: cache-node_modules
        with:
          # caching node_modules
          path: |
            ${{ inputs.workdir }}node_modules
            **/node_modules
            **/.eslintcache
            ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE }}
          key: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          targets: ${{ matrix.target }}

      - name: rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "${{ inputs.workdir }}/src-tauri"
          cache-targets: false

      - name: install frontend dependencies
        run: pnpm install && pnpm eslint --fix . && pnpm prettier --write .

      - id: environments
        name: environments
        run: |
          opt="--no-deps --format-version 1"
          if [ -d "src-tauri" ]; then
            opt="$opt --manifest-path src-tauri/Cargo.toml"
          fi
          echo "
          project=$(cargo metadata $opt | jq -r '.packages[0].name')
          version=$(cargo metadata $opt | jq -r '.packages[0].version')
          " >> "$GITHUB_OUTPUT"
        shell: bash

      
      - id: tauri-action
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ steps.environments.outputs.project }}-v__VERSION__-${{ steps.environments.outputs.version }}
          releaseName: '${{ steps.environments.outputs.project }} v__VERSION__'
          releaseBody: ${{ github.event.head_commit.message }}
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.target }}
