on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"
      GOOS:
        required: false
        default: "linux"
        type: "string"
        description: "GOOS target os"
      GOARCH:
        required: true
        type: "string"
        description: "GOARCH arch"
      ENTRANCE:
        required: false
        default: "main.go"
        type: string
        description: "main.go relative path"

    outputs:
      version:
        description: "golang application version"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    outputs:
      version: ${{ steps.environments.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache: false

      - name: restore golang cache
        uses: actions/cache/restore@v4
        id: cache-restore-golang
        env:
          cache-name: cache-gomod
        with:
          path: |
            ~/go
          key: ${{ runner.os }}-golang-store-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-store-${{ env.cache-name }}-

      - name: download gosec report
        uses: actions/download-artifact@v4
        with:
          name: gosec-report
          path: |
            ${{ inputs.workdir }}build/gosec-report.json

      - name: build binary
        run: |
          mkdir -p build
          CGO_ENABLE=0 GOOS=${{ inputs.GOOS }} GOARCH=${{ inputs.GOARCH }} go build -a -o build/${{ github.repository }} ${{ inputs.ENTRANCE }}

      - name: test
        run: |
          go test -gcflags="all=-N -l" -coverprofile=build/coverage.txt -covermode count -json -v ./... 2>&1 | tee build/test.json | gotestfmt 
          go-junit-report -parser gojson -in build/test.json -out build/report.xml

      - id: environments
        name: environments
        run: |
          version=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)
          echo "version: $version"
          version="${version-0.0.1}-$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"
          echo $version
          echo "
          project=${{ github.repository }}  
          version=$version
          " >> "$GITHUB_OUTPUT"

      - id: sonar
        name: sonar
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ inputs.workdir }}
          args: >
            -Dsonar.projectKey=${{ steps.environments.outputs.project }} 
            -Dsonar.projectVersion=${{ steps.environments.outputs.version }} 
            -Dsonar.go.coverage.reportPaths=build/report.xml

      - name: upload target
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: |
            ${{ inputs.workdir }}build/${{ steps.environments.outputs.project }}
