on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          rustup component add rustfmt clippy
          cargo install cargo-audit cargo-msrv cargo2junit cargo-tarpaulin cargo-nextest
      - name: cache registry cache
        id: heliannuuthus-cargo-cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-heliannuuthus-cargo-cache
