on:
  workflow_call:
    inputs:
      version:
        required: false
        default: "5.0.1.3006"
        type: "string"
        description: "Specify sonar-scanner-cli version"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - id: init
        name: init sonar-scanner-cli
        run: |
          curl -L -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ inputs.version }}-linux.zip
          unzip sonar-scanner.zip
          ls
          echo "~/sonar-scanner-${{ inputs.version }}-linux/bin" >> $GITHUB_PATH