on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: "string"
        description: "Specify all of steps where are run"
    outputs:
      version:
        description: "gradle application version"
        value: ${{ jobs.build.outputs.version }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.environments.outputs.version }}
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: build and test
        run: gradle clean build
        env:
          GPR_USER: ${{ secrets.user }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: environments
        name: environments
        run: |
          echo "
          project=${{ github.repository }}
          version=$(gradle version -q | awk 'NR==1 {print}')
          " >> "$GITHUB_OUTPUT"
      - name: upload target
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: |
            ${{ inputs.workdir }}build/
