name: golang

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]

jobs:
  project:
    uses: ./.github/workflows/call-golang.yml
    permissions:
      contents: read
      packages: write
    with:
      workdir: "tests/golang/"
      ENTRANCE: cmd/main.go

  containerize:
    needs: ["project"]
    uses: ./.github/workflows/call-containerize.yml
    permissions:
      contents: read
      packages: write
    with:
      workdir: "tests/golang/"
      version: ${{ needs.project.outputs.version }}
      targets: "tests/golang/build"
