name: golang

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]

jobs:
  project:
    uses: ./.github/workflows/call-golang.yml
    permissions:
      contents: read
      packages: write
    with:
      golang_workdir: "tests/golang/"
      container_workdir: "tests/golang/"
      ENTRANCE: cmd/main.go
