name: gradle-library

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]

jobs:
  project:
    uses: ./.github/workflows/call-gradle-library.yml
    permissions:
      contents: read
      packages: write
    with:
      workdir: "tests/gradle-cloud-library/"
      user: ${{ github.actor }}
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}