name: gradle

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]

jobs:
  project:
    uses: ./.github/workflows/call-gradle.yml
    permissions:
      contents: read
      packages: write
    with:
      gradle_workdir: "tests/gradle-cloud/"
      container_workdir: "tests/gradle-cloud/"
