name: gradle-library

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]

env:
  PUBLISH_REPOSITORY_NAME: GithubPackage
  PUBLISH_REPOSITORY_URL: https://maven.pkg.github.com/heliannuuthus/integrate-deploy

jobs:
  project:
    uses: ./.github/workflows/call-gradle-library.yml
    permissions:
      contents: read
      packages: write
    with:
      gradle_workdir: "tests/gradle-library/"
      user: ${{ github.actor }}
      PUBLISH_REPOSITORY_NAME: ${{ vars.PUBLISH_REPOSITORY_NAME }}
      PUBLISH_REPOSITORY_URL: ${{ vars.PUBLISH_REPOSITORY_URL }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
