name: gradle

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]

jobs:
  project:
    uses: ./.github/workflows/call-gradle.yml
    permissions:
      contents: read
      packages: write
    with:
      workdir: "tests/gradle-cloud/"

  containerize:
    needs: ["project"]
    uses: ./.github/workflows/call-containerize.yml
    permissions:
      contents: read
      packages: write
    with:
      workdir: "tests/gradle-cloud/"
      version: ${{ needs.project.outputs.version }}
      targets: "tests/gradle-cloud/build"
