name: gradle-cloud

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]

jobs:
  project:
    uses: ./.github/workflows/call-gradle-cloud.yml
    permissions:
      contents: read
      packages: write
    with:
      workdir: "tests/gradle-cloud-cloud/"
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}