name: node

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]
jobs:
  setup:
    uses: ./.github/workflows/call-node-setup.yml
    with:
      workdir: "tests/node/"

  lint:
    if: ${{ github.event.pull_request.merged != true }}
    needs: setup
    uses: ./.github/workflows/call-node-lint.yml
    with:
      workdir: "tests/node/"
      PNPM_STORE: ${{ needs.setup.outputs.PNPM_STORE }}

  build:
    if: ${{ always() && needs.setup.result == 'success' }}
    needs: [setup, lint]
    uses: ./.github/workflows/call-node-build.yml
    with:
      workdir: "tests/node/"
      PNPM_STORE: ${{ needs.setup.outputs.PNPM_STORE }}
