on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    uses: ./.github/workflows/call-rust-lint.yml
    with:
      clippy: true
      workdir: "tests/rust/"
  

  build:
    needs: lint
    uses: ./.github/workflows/call-rust-build.yml
    with:
      workdir: "tests/rust/"


  containeraized:
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/call-containerize.yml
    with:
      version: ${{ needs.build.outputs.version }}
      workdir: "tests/rust/"
      target: "tests/rust/target/release"