name: rust

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]
jobs:
  project:
    uses: ./.github/workflows/call-rust.yml
    permissions:
      contents: read
      packages: write
    with:
      workdir: "tests/rust/"
