name: rust-tauri

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]
jobs:
  project:
    uses: ./.github/workflows/call-rust-tauri.yml
    permissions:
      contents: write
      packages: write
    with:
      workdir: "tests/node/"