name: rust

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]
jobs:
  project:
    uses: ./.github/workflows/call-rust.yml
    permissions:
      contents: read
      packages: write
    with:
      workdir: "tests/rust/"
      
  containerize:
    needs: ["project"]
    uses: ./.github/workflows/call-containerize.yml
    permissions:
      contents: read
      packages: write
    with:
      workdir: "tests/rust/"
      version: ${{ needs.project.outputs.version }}
      targets: "tests/rust/target"