on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]
jobs:
  setup:
    uses: ./.github/workflows/call-rust-setup.yml
    with:
      workdir: "tests/rust/"

  lint:
    if: ${{ ! github.event.pull_request.merged }}
    needs: setup
    uses: ./.github/workflows/call-rust-lint.yml
    with:
      workdir: "tests/rust/"

  build:
    needs: [setup, lint]
    uses: ./.github/workflows/call-rust-build.yml
    with:
      workdir: "tests/rust/"

  containeraized:
    if: ${{ github.event.pull_request.merged }}
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/call-containerize.yml
    with:
      version: ${{ needs.build.outputs.version }}
      workdir: "tests/rust/"
      target: "tests/rust/target/release"
