name: rust

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [closed]
jobs:
  setup:
    uses: ./.github/workflows/call-rust-setup.yml
    with:
      workdir: "tests/rust/"

  lint:
    if: ${{ github.event.pull_request.merged != true }}
    needs: setup
    uses: ./.github/workflows/call-rust-lint.yml
    with:
      workdir: "tests/rust/"

  build:
    if: ${{ always() && needs.setup.result == 'success' && needs.lint.result != 'failure' }}
    needs: [setup, lint]
    uses: ./.github/workflows/call-rust-build.yml
    with:
      workdir: "tests/rust/"

  containeraized:
    if: ${{ always() && github.event.pull_request.merged == true }}
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/call-containerize.yml
    with:
      version: ${{ needs.build.outputs.version }}
      workdir: "tests/rust/"
      target: "tests/rust/target/"
