on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  lint:
    if: ${{ ! github.event.pull_request.merged }}
    uses: ./.github/workflows/call-rust-lint.yml
    with:
      clippy: true
      workdir: "tests/rust/"

  build:
    needs: lint
    uses: ./.github/workflows/call-rust-build.yml
    with:
      workdir: "tests/rust/"

  containeraized:
    if: ${{ github.event.pull_request.merged }}
    needs: build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/call-containerize.yml
    with:
      version: ${{ needs.build.outputs.version }}
      workdir: "tests/rust/"
      target: "tests/rust/target/release"
